apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: train-pipeline-
  namespace: kubeflow
spec:
  entrypoint: train-pipeline
  templates:
  - name: train-pipeline
    dag:
      tasks:
      - name: train-model
        template: train-model-task

  # Define the train-model task
  - name: train-model-task
    container:
      image: gcr.io/{{ secrets.GCP_PROJECT }}/train-image:latest  # Replace with your Docker image
      command:
        - python
        - train.py
      args: []
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/key.json
      volumeMounts:
        - name: gcp-credentials
          mountPath: /app
      resources:
        limits:
          memory: "4Gi"
          cpu: "2"

  # Add volumes to handle GCP credentials
  volumes:
  - name: gcp-credentials
    secret:
      secretName: gcp-sa-key
