name: Train and Deploy via Kubeflow

on:
  push:
    branches:
      - kubeflow

jobs:
  kubeflow-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Authenticate GKE Cluster
        run: gcloud container clusters get-credentials kubeflow-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT }}

      - name: Apply Kubeflow Pipeline
        run: kubectl apply -f ./kubeflow/pipeline.yaml

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/train-image:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/train-image:latest