name: Testing with Pytest (test_data)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Might modify

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/DataPreprocessing" >> $GITHUB_ENV

    - name: Run tests in DataPreprocessing/test/test_data
      run: pytest DataPreprocessing/test/test_data/ --junitxml=pytest-report.xml
      continue-on-error: false

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-test_data
        path: pytest-report.xml

    - name: Notify on success
      if: success()
      run: echo "Tests in test_data folder passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Tests in test_data folder failed"
