name: Conditional Pipeline Execution
 
on:
  workflow_dispatch:  # Allows manual or external trigger
  repository_dispatch:  # Triggered by an external event from the Cloud Function
 
jobs:
  run-pipeline:
    if: github.event.action == 'trigger-pipeline'  # Ensure it runs only for the correct action
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    - name: Execute Pipeline
      run: |
        echo "Condition met! Running the pipeline."
        # Add your pipeline commands here
